package com.github.BambooTuna.AkkaServerSupport.authentication.error

import akka.http.scaladsl.server.Rejection

sealed trait AuthenticationCustomError extends Rejection

sealed trait AuthenticationUseCaseError extends AuthenticationCustomError
case object SignUpInsertError extends AuthenticationUseCaseError
case object SignInIdOrPassWrongError extends AuthenticationUseCaseError
case object CantFoundUserError extends AuthenticationUseCaseError
