package com.github.BambooTuna.AkkaServerSupport.authentication.error

import akka.http.javadsl.server.CustomRejection

sealed trait AuthenticationCustomError extends CustomRejection

case object AccountAlreadyExistsError extends AuthenticationCustomError
case object SignInForbiddenError extends AuthenticationCustomError
case object AccountNotFoundError extends AuthenticationCustomError
case object ActivateAccountError extends AuthenticationCustomError

case object InvalidActivateCodeError extends AuthenticationCustomError
case object InvalidInitializationCodeError extends AuthenticationCustomError
