package com.github.BambooTuna.AkkaServerSupport.authentication.error

import akka.http.javadsl.server.CustomRejection

sealed trait AuthenticationCustomError extends CustomRejection

sealed trait AuthenticationUseCaseError extends AuthenticationCustomError
case object SignUpInsertError extends AuthenticationUseCaseError
case object SignInIdOrPassWrongError extends AuthenticationUseCaseError
case object CantFoundUserError extends AuthenticationUseCaseError
