package com.github.BambooTuna.AkkaServerSupport.authentication.error

import akka.http.scaladsl.server.Rejection

sealed trait OAuth2CustomError extends Rejection
case object ParseParameterFailedError extends OAuth2CustomError

sealed trait AccessTokenAcquisitionUseCaseError extends OAuth2CustomError
case object AccessTokenAcquisitionResponseFailedError
    extends AccessTokenAcquisitionUseCaseError
case object CSRFTokenForbiddenError extends AccessTokenAcquisitionUseCaseError

sealed trait LinkedAuthenticationUseCaseError extends OAuth2CustomError
case object RegisteredError extends LinkedAuthenticationUseCaseError
case object CooperationFailureError extends LinkedAuthenticationUseCaseError
case object AccountNotFoundError extends LinkedAuthenticationUseCaseError

sealed trait AccessTokenAcquisitionResponseParserError extends OAuth2CustomError
case object ParseToRegisterCommandError
    extends AccessTokenAcquisitionResponseParserError
case object ParseToSignInCommandError
    extends AccessTokenAcquisitionResponseParserError
